### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by chiho-5**
Using concurrently to run both client and server simultaneously

### CODE REVIEW

**Comment by ihtasham42** [comment]
Hi, thanks for the PR. Could you add the heroku-postbuild line back in?

**Comment by tareita** [comment]
trash

**Comment by chiho-5** [comment]
> trash

Was a mistake. 
Made a PR without completing the code

**Comment by chiho-5** [comment]
> Hi, thanks for the PR. Could you add the heroku-postbuild line back in?

Sure thing. Sorry for the incomplete code

**Comment by ihtasham42** [comment]
> > Hi, thanks for the PR. Could you add the heroku-postbuild line back in?
> 
> Sure thing. Sorry for the incomplete code

Sorry the ``"heroku-postbuild": "cd client && npm install && npm run build"`` line still seems to be missing. Also there's a period at the end of line 8 which breaks the code json file.

**Comment by ihtasham42** [comment]
If possible could you reopen with these changes? Thanks

**Pull request merged**
